// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsvetgtwrqugkrqgzxjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzdmV0Z3R3cnF1Z2tycWd6eGpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDQzNjksImV4cCI6MjA3MDMyMDM2OX0.VQkw7VKRoagtU2Y3FhAT6FUcL081mNVAAedLgSDZiCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});