name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main
    paths:
      - "supabase/functions/send-email/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Supabase Login
        run: |
          supabase login
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Link Supabase Project
        run: |
          supabase link --project-ref dsvetgtwrqugkrqgzxjb
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Set Supabase Secrets
        run: |
          supabase secrets set ZEPTOMAIL_TOKEN="${{ secrets.ZEPTOMAIL_TOKEN }}"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy Edge Function
        run: |
          supabase functions deploy send-email
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
